# Generated by Django 6.0.1 on 2026-02-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('tigopesa', 'Tigo Pesa'), ('airtel', 'Airtel Money'), ('crdb', 'CRDB'), ('nmb', 'NMB'), ('cash', 'Cash')], default='mpesa', max_length=20),
        ),
    ]
